## docker-compose.yml

# 도커 컨테이너 관리
# 이미지 관리를 도와줌
# 이 파일은 개발용으로 사용 DEV=true로 바뀌면서 flake8 설치
# deploy.yml 는 배포용으로 사용
# 장고는 8000 포트를 사용하니까 우리도 8000 포트
# 우리의 8000포트는 컨테이너의 8000 포트로 맵핑
# volumes:저장공간 루트폴더의 app:가상환경 app
# Command : 0.0.0.0 모든 아이피 주소에서 8000포트로 접근 가능 127.0.0.1은 로컬에서만 가능하도록 설정
# 도커 컴포즈 파일을 빌드 : docker-compose build

version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"